#!/bin/bash

# Тест услуги "Переадресация безусловная" - CFU. 
# 
# Условия теста: создано два SIP-абонента и один SIP-транк
#              : активированы услуги (выполнен скрипт sswconf_ss_perm.sh)

# Переменные командной строки
# $EXTER_IP SSW_IP_address
# $IP SIPP_IP_address

.  tests/ssw342/conf_cf

# Путь к скриптам
ROOT_DIR=$(pwd)
SRC_PATH=$ROOT_DIR/tests/ssw342/cfu
create_dir $SRC_PATH/temp
TEMP_PATH=$SRC_PATH/temp
create_file $TEMP_PATH/ex_code.txt
create_dir log/ssw342_cfu
LOG_PATH=log/ssw342_cfu

create_file $LOG_PATH/log.txt

# Путь к sipp
#SIPP_PATH=../../../opt/sipp

# Переменные для подсчета успешных, неуспешных вызовов и номер теста
FAIL_COUNT=0
SUCC_COUNT=0
COUNT=0

# Функция исключениянескольких элементов
IGNORE ()
{
if test $COUNT -eq 3
   then
     COUNT=$(($COUNT+1))
fi                  
if test $COUNT -eq 7
   then
     COUNT=$(($COUNT+1))
fi    
}

for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do 
# Создаем файлы с данными
echo "SEQUENTIAL;
${USER_MASS[$COUNT]};${USER_DOM_MASS[$COUNT]};*$CFU_KOD*${USER_MASS[$(($COUNT+1))]}#;*#$CFU_KOD#;#$CFU_KOD#;*$CFU_KOD#;" > $TEMP_PATH/${USER_MASS[$COUNT]}.csv
done

# Создаем файлы с данными
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[7]};${USER_MASS[0]};" > $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[0]}.csv
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[7]};${USER_MASS[1]};" > $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[1]}.csv  
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[7]};${USER_MASS[2]};" > $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[2]}.csv  
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[7]};${USER_MASS[8]};" > $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[8]}.csv  
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[7]};${USER_MASS[9]};" > $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[9]}.csv  
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[7]};${USER_MASS[10]};" > $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[10]}.csv  

echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[0]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[0]}.csv  
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[1]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[1]}.csv
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[2]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[2]}.csv
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[4]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[4]}.csv  
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[5]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[5]}.csv 
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[6]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[6]}.csv 
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[8]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[8]}.csv 
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[9]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[9]}.csv 
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[10]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[10]}.csv 

echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[11]};${USER_MASS[0]};" > $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[0]}.csv
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[11]};${USER_MASS[1]};" > $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[1]}.csv
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[11]};${USER_MASS[2]};" > $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[2]}.csv
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[11]};${USER_MASS[4]};" > $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[4]}.csv
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[11]};${USER_MASS[5]};" > $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[5]}.csv
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[11]};${USER_MASS[6]};" > $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[6]}.csv

echo "SEQUENTIAL;
${USER_MASS[10]};${USER_DOM_MASS[10]};*$CFU_KOD*${USER_MASS[0]}#;" > $TEMP_PATH/${USER_MASS[10]}-max.csv

echo "SEQUENTIAL;
${USER_MASS[0]};${USER_DOM_MASS[0]};*$CFU_KOD*$USER_NR#;" > $TEMP_PATH/${USER_MASS[0]}-$USER_NR.csv
echo "SEQUENTIAL;
${USER_MASS[1]};${USER_DOM_MASS[1]};*$CFU_KOD*$USER_UA#;" > $TEMP_PATH/${USER_MASS[1]}-$USER_UA.csv 
echo "SEQUENTIAL;
${USER_MASS[2]};${USER_DOM_MASS[2]};*$CFU_KOD*$USER_NN#;" > $TEMP_PATH/${USER_MASS[2]}-$USER_NN.csv 

FINISH ()
{
# Unregistration
for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do
T_NAME="Unregistration ${USER_MASS[$COUNT]}"
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/${USER_MASS[$COUNT]}.csv -mi $IP -s ${AUTH_MASS[$COUNT]} -ap ${PASS_MASS[$COUNT]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[$COUNT]} -recv_timeout 200s -timeout_error
REZULT_A
done

# Удаляем файлы с данными (на случай, если они не были удалены)
for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do
sudo rm $TEMP_PATH/${USER_MASS[$COUNT]}.csv
done

# Удаляем файлы с данными
sudo rm $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[0]}.csv
sudo rm $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[1]}.csv
sudo rm $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[2]}.csv
sudo rm $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[8]}.csv
sudo rm $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[9]}.csv
sudo rm $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[10]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[0]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[1]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[2]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[4]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[5]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[6]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[8]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[9]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[10]}.csv
sudo rm $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[0]}.csv
sudo rm $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[1]}.csv
sudo rm $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[2]}.csv
sudo rm $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[4]}.csv
sudo rm $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[5]}.csv
sudo rm $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[6]}.csv
sudo rm $TEMP_PATH/${USER_MASS[10]}-max.csv
sudo rm $TEMP_PATH/${USER_MASS[0]}-$USER_NR.csv
sudo rm $TEMP_PATH/${USER_MASS[1]}-$USER_UA.csv
sudo rm $TEMP_PATH/${USER_MASS[2]}-$USER_NN.csv

#    Читаем exit коды, чтобы убедиться, что все UAS отработали корректно.
EX_FAIL=0
while read line;do
     excode=`echo $line | cut -d ' ' -f 3`
     name=`echo $line | cut -d ' ' -f 1`
     echo "[DEBUG] Exit code from test $name equal $excode" >> $LOG_PATH/log.txt
     if [ "$excode" != "0" ];then
        EX_FAIL=1
        FAIL_COUNT=$(($FAIL_COUNT+1))
     fi
done < $TEMP_PATH/ex_code.txt

sudo rm $TEMP_PATH/ex_code.txt

# Вывод результата  
echo "Success $SUCC_COUNT, Failed $FAIL_COUNT"  

  if [[ $EX_FAIL -eq 0 && $FAIL_COUNT -eq 0 ]]
        then 
        exit 0
        else 
        exit 1
  fi
}

# Функция подсчета успешных и неуспешных вызовов
REZULT_A ()
{
if test $? -eq 0
      then
        SUCC_COUNT=$(($SUCC_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A passed" >> $LOG_PATH/log.txt
      else
        FAIL_COUNT=$(($FAIL_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A failed" >> $LOG_PATH/log.txt
fi
}

# Function finishing script
FATAL ()
{
sudo killall -9 screen
screen -wipe
sudo killall -9 sipp
FAIL_COUNT=$(($FAIL_COUNT+999))
}

FUNC_TEST ()
{
        start_screen "$COUNT$T_NAME" "$COMMAND"  
        sleep 0.5
        check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else   
                $COMMAND_A
                REZULT_A
                wait_uas "$COUNT$T_NAME" 10
                if test $? -eq 99;then 
                        echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                        FATAL
                        FINISH
                fi
                sleep 2
        fi
}

for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do
# Registration users
T_NAME="Registration ${USER_MASS[$COUNT]}"
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/${USER_MASS[$COUNT]}.csv -mi $IP -s ${AUTH_MASS[$COUNT]} -ap ${PASS_MASS[$COUNT]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[$COUNT]} -recv_timeout 200s -timeout_error
REZULT_A
done

for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do
IGNORE
# Activation feature
T_NAME="Activation ${USER_MASS[$COUNT]}"
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/uac_field2.xml -inf $TEMP_PATH/${USER_MASS[$COUNT]}.csv -mi $IP -s ${AUTH_MASS[$COUNT]} -ap ${PASS_MASS[$COUNT]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[$COUNT]} -recv_timeout 200s -timeout_error
REZULT_A
done


T_NAME="Max_redirect__5"
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/uac_field2.xml -inf $TEMP_PATH/${USER_MASS[10]}-max.csv -mi $IP -s ${AUTH_MASS[10]} -ap ${PASS_MASS[10]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error
REZULT_A
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[9]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST
sleep 2

T_NAME="Max_redirect__5_With_PRACK"
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2-uac_181_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[9]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST
sleep 2

sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/uac_field2_483.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[8]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error   
REZULT_A
sleep 2

for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do
IGNORE
T_NAME="Deactivation ${USER_MASS[$COUNT]}"
# Deactivation feature
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/uac_field4.xml -inf $TEMP_PATH/${USER_MASS[$COUNT]}.csv -mi $IP -s ${AUTH_MASS[$COUNT]} -ap ${PASS_MASS[$COUNT]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[$COUNT]} -recv_timeout 200s -timeout_error
REZULT_A
done


FINISH

