#!/bin/bash

# Тест услуги "Переадресация по занятости" - CFB. Версия ПО 3.3.
# 
# Условия теста: создано два SIP-абонента и один SIP-транк
#              : активированы услуги (выполнен скрипт sswconf_ss_perm.sh)

# Переменные командной строки
# $EXTER_IP:$EXTER_PORT SSW_IP_address
# $IP SIPP_IP_address

. ./conf

# Библиотеки
source $LIB_PATH/screen_lib.sh
source $LIB_PATH/create_lib.sh

# Путь к скриптам
ROOT_DIR=$(pwd)
SRC_PATH=$ROOT_DIR/$SCRYPT_PATH/cfb
create_dir $SRC_PATH/temp
TEMP_PATH=$SRC_PATH/temp
create_file $TEMP_PATH/ex_code.txt
create_dir log/ssw350_cfb
LOG_PATH=log/ssw350_cfb

create_file $LOG_PATH/log.txt

# Путь к sipp
#SIPP_PATH=../../../opt/sipp

# Переменные для подсчета успешных, неуспешных вызовов и номер теста
FAIL_COUNT=0
SUCC_COUNT=0
COUNT=0

# Функция исключениянескольких элементов
IGNORE ()
{
if test $COUNT -eq 3
   then
     COUNT=$(($COUNT+1))
fi                  
if test $COUNT -eq 7
   then
     COUNT=$(($COUNT+1))
fi    
}

for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do 
# Создаем файлы с данными
echo "SEQUENTIAL;
${USER_MASS[$COUNT]};${USER_DOM_MASS[$COUNT]};*$CFB_KOD*${USER_MASS[$(($COUNT+1))]}#;*#$CFB_KOD#;#$CFB_KOD#;*$CFB_KOD#;" > $TEMP_PATH/${USER_MASS[$COUNT]}.csv
done

# Создаем файлы с данными
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[7]};${USER_MASS[0]};" > $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[0]}.csv
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[7]};${USER_MASS[1]};" > $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[1]}.csv  
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[7]};${USER_MASS[2]};" > $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[2]}.csv  
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[7]};${USER_MASS[8]};" > $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[8]}.csv  
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[7]};${USER_MASS[9]};" > $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[9]}.csv  
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[7]};${USER_MASS[10]};" > $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[10]}.csv  

echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[0]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[0]}.csv  
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[1]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[1]}.csv
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[2]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[2]}.csv
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[4]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[4]}.csv  
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[5]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[5]}.csv 
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[6]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[6]}.csv 
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[8]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[8]}.csv 
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[9]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[9]}.csv 
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[3]};${USER_MASS[10]};" > $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[10]}.csv 

echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[11]};${USER_MASS[0]};" > $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[0]}.csv
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[11]};${USER_MASS[1]};" > $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[1]}.csv
echo "SEQUENTIAL;
${USER_MASS[7]};${USER_DOM_MASS[11]};${USER_MASS[2]};" > $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[2]}.csv
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[11]};${USER_MASS[4]};" > $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[4]}.csv
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[11]};${USER_MASS[5]};" > $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[5]}.csv
echo "SEQUENTIAL;
${USER_MASS[3]};${USER_DOM_MASS[11]};${USER_MASS[6]};" > $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[6]}.csv

echo "SEQUENTIAL;
${USER_MASS[10]};${USER_DOM_MASS[10]};*$CFB_KOD*${USER_MASS[0]}#;" > $TEMP_PATH/${USER_MASS[10]}-max.csv

echo "SEQUENTIAL;
${USER_MASS[0]};${USER_DOM_MASS[0]};*$CFB_KOD*$USER_NR#;" > $TEMP_PATH/${USER_MASS[0]}-$USER_NR.csv
echo "SEQUENTIAL;
${USER_MASS[1]};${USER_DOM_MASS[1]};*$CFB_KOD*$USER_UA#;" > $TEMP_PATH/${USER_MASS[1]}-$USER_UA.csv 
echo "SEQUENTIAL;
${USER_MASS[2]};${USER_DOM_MASS[2]};*$CFB_KOD*$USER_NN#;" > $TEMP_PATH/${USER_MASS[2]}-$USER_NN.csv 

FINISH ()
{
# Unregistration
for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do
T_NAME="Unregistration ${USER_MASS[$COUNT]}"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/${USER_MASS[$COUNT]}.csv -mi $IP -s ${AUTH_MASS[$COUNT]} -ap ${PASS_MASS[$COUNT]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[$COUNT]} -recv_timeout 200s -timeout_error
REZULT_A
done

# Удаляем файлы с данными (на случай, если они не были удалены)
for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do
sudo rm $TEMP_PATH/${USER_MASS[$COUNT]}.csv
done

# Удаляем файлы с данными
sudo rm $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[0]}.csv
sudo rm $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[1]}.csv
sudo rm $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[2]}.csv
sudo rm $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[8]}.csv
sudo rm $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[9]}.csv
sudo rm $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[10]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[0]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[1]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[2]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[4]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[5]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[6]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[8]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[9]}.csv
sudo rm $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[10]}.csv
sudo rm $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[0]}.csv
sudo rm $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[1]}.csv
sudo rm $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[2]}.csv
sudo rm $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[4]}.csv
sudo rm $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[5]}.csv
sudo rm $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[6]}.csv
sudo rm $TEMP_PATH/${USER_MASS[10]}-max.csv
sudo rm $TEMP_PATH/${USER_MASS[0]}-$USER_NR.csv
sudo rm $TEMP_PATH/${USER_MASS[1]}-$USER_UA.csv
sudo rm $TEMP_PATH/${USER_MASS[2]}-$USER_NN.csv

#    Читаем exit коды, чтобы убедиться, что все UAS отработали корректно.
EX_FAIL=0
while read line;do
     excode=`echo $line | cut -d ' ' -f 3`
     name=`echo $line | cut -d ' ' -f 1`
     echo "[DEBUG] Exit code from test $name equal $excode" >> $LOG_PATH/log.txt
     if [ "$excode" != "0" ];then
        EX_FAIL=1
        FAIL_COUNT=$(($FAIL_COUNT+1))
     fi
done < $TEMP_PATH/ex_code.txt

sudo rm $TEMP_PATH/ex_code.txt

# Вывод результата  
echo "Success $SUCC_COUNT, Failed $FAIL_COUNT"  

  if [[ $EX_FAIL -eq 0 && $FAIL_COUNT -eq 0 ]]
        then 
        exit 0
        else 
        exit 1
  fi
}

# Функция подсчета успешных и неуспешных вызовов
REZULT_A ()
{
if test $? -eq 0
      then
        SUCC_COUNT=$(($SUCC_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A passed" >> $LOG_PATH/log.txt
      else
        FAIL_COUNT=$(($FAIL_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A failed" >> $LOG_PATH/log.txt
fi
}

# Function finishing script
FATAL ()
{
sudo killall -9 screen
screen -wipe
sudo killall -9 sipp
FAIL_COUNT=$(($FAIL_COUNT+999))
}

FUNC_TEST ()
{
        start_screen "$COUNT$T_NAME" "$COMMAND"  
        sleep 0.5
        check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else   
                $COMMAND_A
                REZULT_A
                wait_uas "$COUNT$T_NAME" 10
                if test $? -eq 99;then 
                        echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                        FATAL
                        FINISH
                fi
                sleep 2
        fi
}


for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do
# Registration users
T_NAME="Registration ${USER_MASS[$COUNT]}"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/${USER_MASS[$COUNT]}.csv -mi $IP -s ${AUTH_MASS[$COUNT]} -ap ${PASS_MASS[$COUNT]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[$COUNT]} -recv_timeout 200s -timeout_error
REZULT_A
done

for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do
IGNORE
T_NAME="Activation ${USER_MASS[$COUNT]}"
# Activation feature
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2.xml -inf $TEMP_PATH/${USER_MASS[$COUNT]}.csv -mi $IP -s ${AUTH_MASS[$COUNT]} -ap ${PASS_MASS[$COUNT]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[$COUNT]} -recv_timeout 200s -timeout_error
REZULT_A
done

echo "CFB once and with PRACK" >> $LOG_PATH/log.txt
COUNT=0
while [ $COUNT -lt 3 ] 
do
COUNT=$(($COUNT+1))

T_NAME=a-b
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[2]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=a-c
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[10]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=b-a
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[6]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[6]}.csv -mi $IP -s ${AUTH_MASS[3]} -ap ${PASS_MASS[3]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=b-c
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[10]}.csv -mi $IP -s ${AUTH_MASS[3]} -ap ${PASS_MASS[3]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=c-a
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[2]}.csv -mi $IP -s ${AUTH_MASS[11]} -ap ${PASS_MASS[11]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=c-b
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[6]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[6]}.csv -mi $IP -s ${AUTH_MASS[11]} -ap ${PASS_MASS[11]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error"
FUNC_TEST

done

echo "CFB twice" >> $LOG_PATH/log.txt
T_NAME=a-b
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[1]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=a-c
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[9]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[9]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=b-a
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[5]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[6]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[5]}.csv -mi $IP -s ${AUTH_MASS[3]} -ap ${PASS_MASS[3]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=b-c
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[9]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[9]}.csv -mi $IP -s ${AUTH_MASS[3]} -ap ${PASS_MASS[3]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=c-a
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[1]}.csv -mi $IP -s ${AUTH_MASS[11]} -ap ${PASS_MASS[11]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=c-b
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[5]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[6]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[5]}.csv -mi $IP -s ${AUTH_MASS[11]} -ap ${PASS_MASS[11]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error"
FUNC_TEST

echo CFB_three >> $LOG_PATH/log.txt
T_NAME=a-b
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[0]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[0]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=a-c
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[8]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[9]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[8]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=b-a
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[4]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[5]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[6]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[4]}.csv -mi $IP -s ${AUTH_MASS[3]} -ap ${PASS_MASS[3]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=b-c
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[8]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[9]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[8]}.csv -mi $IP -s ${AUTH_MASS[3]} -ap ${PASS_MASS[3]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=c-a
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[0]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[0]}.csv -mi $IP -s ${AUTH_MASS[11]} -ap ${PASS_MASS[11]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=c-b
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[4]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[5]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[6]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[4]}.csv -mi $IP -s ${AUTH_MASS[11]} -ap ${PASS_MASS[11]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error"
FUNC_TEST

echo "To busy, to unavailable" >> $LOG_PATH/log.txt
COUNT=5
while [ $COUNT -lt 7 ]
do
COUNT=$(($COUNT+1))
T_NAME=a-b
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[0]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[0]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=a-c
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[8]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[9]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[8]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=b-a
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[4]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[5]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[6]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[4]}.csv -mi $IP -s ${AUTH_MASS[3]} -ap ${PASS_MASS[3]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=b-c
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[8]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[9]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[8]}.csv -mi $IP -s ${AUTH_MASS[3]} -ap ${PASS_MASS[3]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=c-a
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[0]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[0]}.csv -mi $IP -s ${AUTH_MASS[11]} -ap ${PASS_MASS[11]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=c-b
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[4]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[5]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[6]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[4]}.csv -mi $IP -s ${AUTH_MASS[11]} -ap ${PASS_MASS[11]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error"
FUNC_TEST

done

T_NAME="Max_redirect__5"
COUNT=8
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2.xml -inf $TEMP_PATH/${USER_MASS[10]}-max.csv -mi $IP -s ${AUTH_MASS[10]} -ap ${PASS_MASS[10]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error
REZULT_A

COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[9]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[0]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[9]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME="Max_redir_With_PRACK"
COUNT=9
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[9]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[0]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/2-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/2-uac_181_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[9]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=10
T_NAME=Max_cout_exceed
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[8]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[9]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[10]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[0]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_483.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[8]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST

echo "Not register, Unallocated, No number" >> $LOG_PATH/log.txt
COUNT=11
T_NAME=set_new_num
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2.xml -inf $TEMP_PATH/${USER_MASS[0]}-$USER_NR.csv -mi $IP -s ${AUTH_MASS[0]} -ap ${PASS_MASS[0]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[0]} -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2.xml -inf $TEMP_PATH/${USER_MASS[1]}-$USER_UA.csv -mi $IP -s ${AUTH_MASS[1]} -ap ${PASS_MASS[1]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2.xml -inf $TEMP_PATH/${USER_MASS[2]}-$USER_NN.csv -mi $IP -s ${AUTH_MASS[2]} -ap ${PASS_MASS[2]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error
REZULT_A

T_NAME=a-nr
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[0]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/11-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[0]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=b-nr
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[0]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/11-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[0]}.csv -mi $IP -s ${AUTH_MASS[3]} -ap ${PASS_MASS[3]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=c-nr
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[0]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/11-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[0]}.csv -mi $IP -s ${AUTH_MASS[11]} -ap ${PASS_MASS[11]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error    "
FUNC_TEST

T_NAME=a-ua
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/12-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[1]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=b-ua
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/12-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[1]}.csv -mi $IP -s ${AUTH_MASS[3]} -ap ${PASS_MASS[3]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=c-ua
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[1]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/12-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[1]}.csv -mi $IP -s ${AUTH_MASS[11]} -ap ${PASS_MASS[11]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=a-nn
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/13-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[7]}-${USER_MASS[2]}.csv -mi $IP -s ${AUTH_MASS[7]} -ap ${PASS_MASS[7]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[7]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=b-nn
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/13-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[3]}-${USER_MASS[2]}.csv -mi $IP -s ${AUTH_MASS[3]} -ap ${PASS_MASS[3]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[3]} -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME=c-nn
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/6-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p ${PORT_MASS[2]} -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/13-uac_ssw.xml -inf $TEMP_PATH/${USER_MASS[11]}-${USER_MASS[2]}.csv -mi $IP -s ${AUTH_MASS[11]} -ap ${PASS_MASS[11]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[11]} -recv_timeout 200s -timeout_error"
FUNC_TEST

for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do
IGNORE
# Control feature
T_NAME="Control ${USER_MASS[$COUNT]}"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field3.xml -inf $TEMP_PATH/${USER_MASS[$COUNT]}.csv -mi $IP -s ${AUTH_MASS[$COUNT]} -ap ${PASS_MASS[$COUNT]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[$COUNT]} -recv_timeout 200s -timeout_error
REZULT_A
done

for (( COUNT=0; COUNT<${#PORT_MASS[*]}-1; COUNT++ ));
do
IGNORE
# Deactivation feature
T_NAME="Deactivation ${USER_MASS[$COUNT]}"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field4.xml -inf $TEMP_PATH/${USER_MASS[$COUNT]}.csv -mi $IP -s ${AUTH_MASS[$COUNT]} -ap ${PASS_MASS[$COUNT]} -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p ${PORT_MASS[$COUNT]} -recv_timeout 200s -timeout_error
REZULT_A
done

FINISH
