#!/bin/bash

# Тест базовых вызовов. Версия ПО 3.4.2
#
# Условия теста: создано два SIP-абонента и один SIP-транк

# Переменные командной строки
# $DEV_USER SSW_cocon_user
# $DEV_PASS SSW_cocon_password
# $DEV_DOMAIN SSW_domain
# $EXTER_IP SSW_IP_address
# $IP SIPP_IP_address

. ../conf

# Путь к скриптам
ROOT_DIR=$(pwd)
SRC_PATH=$ROOT_DIR
TEMP_PATH=$ROOT_DIR/temp

# Путь к sipp
#SIPP_PATH=../../../opt/sipp

# Конфигурируем необходимые таймеры
$SRC_PATH/sswconf_basic1.sh $DEV_USER $DEV_PASS $DEV_DOMAIN $EXTER_IP

# Удаляем файлы с данными (на случай, если они не были удалены)
sudo rm $TEMP_PATH/$USER_A.csv
sudo rm $TEMP_PATH/$USER_B.csv
sudo rm $TEMP_PATH/$USER_C.csv
sudo rm $TEMP_PATH/$USER_A-$USER_B.csv
sudo rm $TEMP_PATH/$USER_A-$USER_C.csv
sudo rm $TEMP_PATH/$USER_B-$USER_A.csv
sudo rm $TEMP_PATH/$USER_B-$USER_C.csv
sudo rm $TEMP_PATH/$USER_C-$USER_A.csv
sudo rm $TEMP_PATH/$USER_C-$USER_B.csv
sudo rm $TEMP_PATH/$USER_A-$USER_NR.csv
sudo rm $TEMP_PATH/$USER_A-$USER_UA.csv
sudo rm $TEMP_PATH/$USER_A-$USER_NN.csv
sudo rm $TEMP_PATH/$USER_B-$USER_NR.csv
sudo rm $TEMP_PATH/$USER_B-$USER_UA.csv
sudo rm $TEMP_PATH/$USER_B-$USER_NN.csv
sudo rm $TEMP_PATH/$USER_C-$USER_NR.csv
sudo rm $TEMP_PATH/$USER_C-$USER_UA.csv
sudo rm $TEMP_PATH/$USER_C-$USER_NN.csv

# Удаляем файл (необходим для поиска ошибки) с результатами по каждому тесту
sudo rm $LOG_PATH/results_basic.txt

# Создаем файлы с данными
echo "SEQUENTIAL;
$USER_A;$DOM_A;" > $TEMP_PATH/$USER_A.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;" > $TEMP_PATH/$USER_B.csv
echo "SEQUENTIAL;
$USER_C;$DOM_C;" > $TEMP_PATH/$USER_C.csv
echo "SEQUENTIAL;
$USER_A;$DOM_A;$USER_B;" > $TEMP_PATH/$USER_A-$USER_B.csv
echo "SEQUENTIAL;
$USER_A;$DOM_A;$USER_C;" > $TEMP_PATH/$USER_A-$USER_C.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;$USER_A;" > $TEMP_PATH/$USER_B-$USER_A.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;$USER_C;" > $TEMP_PATH/$USER_B-$USER_C.csv
echo "SEQUENTIAL;
$USER_C;$DOM_C;$USER_A;" > $TEMP_PATH/$USER_C-$USER_A.csv
echo "SEQUENTIAL;
$USER_C;$DOM_C;$USER_B;" > $TEMP_PATH/$USER_C-$USER_B.csv
echo "SEQUENTIAL;
$USER_A;$DOM_A;$USER_NR;" > $TEMP_PATH/$USER_A-$USER_NR.csv
echo "SEQUENTIAL;
$USER_A;$DOM_A;$USER_UA;" > $TEMP_PATH/$USER_A-$USER_UA.csv
echo "SEQUENTIAL;
$USER_A;$DOM_A;$USER_NN;" > $TEMP_PATH/$USER_A-$USER_NN.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;$USER_NR;" > $TEMP_PATH/$USER_B-$USER_NR.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;$USER_UA;" > $TEMP_PATH/$USER_B-$USER_UA.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;$USER_NN;" > $TEMP_PATH/$USER_B-$USER_NN.csv
echo "SEQUENTIAL;
$USER_C;$DOM_C;$USER_NR;" > $TEMP_PATH/$USER_C-$USER_NR.csv
echo "SEQUENTIAL;
$USER_C;$DOM_C;$USER_UA;" > $TEMP_PATH/$USER_C-$USER_UA.csv
echo "SEQUENTIAL;
$USER_C;$DOM_C;$USER_NN;" > $TEMP_PATH/$USER_C-$USER_NN.csv

# Переменные для подсчета успешных, неуспешных вызовов и номер теста
FAIL_COUNT=0
SUCC_COUNT=0
COUNT=0

# Функция подсчета успешных и неуспешных вызовов
REZULT ()
{
  if test $? -ne 0
      then
          FAIL_COUNT=$(($FAIL_COUNT+1))
          echo Test $COUNT $T_NAME failed >> $LOG_PATH/results_basic.txt
      else
          SUCC_COUNT=$(($SUCC_COUNT+1))
          echo Test $COUNT $T_NAME passed >> $LOG_PATH/results_basic.txt
  fi
}

# Тест
T_NAME=Registration
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_A.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_B.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT

	COUNT=4
        T_NAME=Call_A-B
	sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/$COUNT-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error &
	sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/$COUNT-uac_ssw.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
	REZULT
	sleep 5

# Удаляем файлы с данными
sudo rm $TEMP_PATH/$USER_A.csv
sudo rm $TEMP_PATH/$USER_B.csv
sudo rm $TEMP_PATH/$USER_C.csv
sudo rm $TEMP_PATH/$USER_A-$USER_B.csv 
sudo rm $TEMP_PATH/$USER_A-$USER_C.csv 
sudo rm $TEMP_PATH/$USER_B-$USER_A.csv 
sudo rm $TEMP_PATH/$USER_B-$USER_C.csv 
sudo rm $TEMP_PATH/$USER_C-$USER_A.csv 
sudo rm $TEMP_PATH/$USER_C-$USER_B.csv 
sudo rm $TEMP_PATH/$USER_A-$USER_NR.csv
sudo rm $TEMP_PATH/$USER_A-$USER_UA.csv
sudo rm $TEMP_PATH/$USER_A-$USER_NN.csv
sudo rm $TEMP_PATH/$USER_B-$USER_NR.csv
sudo rm $TEMP_PATH/$USER_B-$USER_UA.csv
sudo rm $TEMP_PATH/$USER_B-$USER_NN.csv
sudo rm $TEMP_PATH/$USER_C-$USER_NR.csv
sudo rm $TEMP_PATH/$USER_C-$USER_UA.csv
sudo rm $TEMP_PATH/$USER_C-$USER_NN.csv

# Возвращаем исходные значения некоторым таймерам
$SRC_PATH/sswconf_basic2.sh $DEV_USER $DEV_PASS $DEV_DOMAIN $EXTER_IP

# Вывод результата  
echo "Success $SUCC_COUNT, Failed $FAIL_COUNT"	

  if test $FAIL_COUNT -ne 0
        then 
        exit 1
        else 
        exit 0
  fi
