#!/bin/bash

# Тест pickup.
# 
# Условия теста: создано два SIP-абонента 
#              : активированы услуги (выполнен скрипт sswconf_ss_perm.sh)

# Переменные командной строки
# $DEV_USER SSW_cocon_user
# $DEV_PASS SSW_cocon_password
# $DEV_DOMAIN SSW_domain
# $EXTER_IP SSW_IP_address
# $IP SIPP_IP_address

. tests/scripts/ssw342/conf

# Путь к скриптам
ROOT_DIR=$(pwd)
SRC_PATH=$ROOT_DIR/tests/scripts/ssw342/pickup
create_dir $SRC_PATH/temp
TEMP_PATH=$SRC_PATH/temp
create_file $TEMP_PATH/ex_code.txt
create_dir log/ssw342_pickup
LOG_PATH=log/ssw342_pickup

create_file $LOG_PATH/log.txt

# Путь к sipp
#SIPP_PATH=../../../opt/sipp

# Переменные для подсчета успешных, неуспешных вызовов и номер теста
FAIL_COUNT=0
SUCC_COUNT=0
COUNT=0

# Создаем файлы с данными
echo "SEQUENTIAL;
$USER_A;$DOM_A;$USER_C_PK" > $TEMP_PATH/$USER_A-$USER_C_PK.csv
echo "SEQUENTIAL;
$USER_A;$DOM_A;$USER_D_PK" > $TEMP_PATH/$USER_A-$USER_D_PK.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;*$PK_KOD2#" > $TEMP_PATH/$USER_B-pk.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;*$PK_KOD1*1#" > $TEMP_PATH/$USER_B-pk1.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;*$PK_KOD1*2#" > $TEMP_PATH/$USER_B-pk2.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;*$PK_KOD1*$USER_C_PK#" > $TEMP_PATH/$USER_B-pkC.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;*$PK_KOD1*$USER_D_PK#" > $TEMP_PATH/$USER_B-pkD.csv
echo "SEQUENTIAL;
$USER_C_PK;$DOM_C_PK;" > $TEMP_PATH/$USER_C_PK.csv
echo "SEQUENTIAL;
$USER_D_PK;$DOM_D_PK;" > $TEMP_PATH/$USER_D_PK.csv

FINISH ()
{
# деактивируем услугу
T_NAME=Deconfigure
$SRC_PATH/sswconf_pickup2.sh $DEV_USER $DEV_PASS $DEV_DOMAIN $EXTER_IP $USER_A $USER_B $USER_C_PK $USER_D_PK
REZULT_A

# Unregistration
COUNT=$(($COUNT+1))
T_NAME=UnRegistration
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/$USER_A-$USER_C_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/$USER_B-pk.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error 
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/$USER_C_PK.csv -mi $IP -s $AUTH_C_PK -ap $PASS_C_PK -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error     
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/$USER_D_PK.csv -mi $IP -s $AUTH_D_PK -ap $PASS_D_PK -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_D_PK -recv_timeout 200s -timeout_error     
REZULT_A

# Удаляем файлы с данными
sudo rm $TEMP_PATH/$USER_A-$USER_C_PK.csv
sudo rm $TEMP_PATH/$USER_A-$USER_D_PK.csv
sudo rm $TEMP_PATH/$USER_B-pk.csv
sudo rm $TEMP_PATH/$USER_B-pk1.csv
sudo rm $TEMP_PATH/$USER_B-pk2.csv
sudo rm $TEMP_PATH/$USER_B-pkC.csv
sudo rm $TEMP_PATH/$USER_B-pkD.csv
sudo rm $TEMP_PATH/$USER_C_PK.csv 
sudo rm $TEMP_PATH/$USER_D_PK.csv 

#    Читаем exit коды, чтобы убедиться, что все UAS отработали корректно.
EX_FAIL=0
while read line;do
     excode=`echo $line | cut -d ' ' -f 3`
     name=`echo $line | cut -d ' ' -f 1`
     echo "[DEBUG] Exit code from test $name equal $excode" >> $LOG_PATH/log.txt
     if [ "$excode" != "0" ];then
        EX_FAIL=1
        FAIL_COUNT=$(($FAIL_COUNT+1))
     fi
done < $TEMP_PATH/ex_code.txt

sudo rm $TEMP_PATH/ex_code.txt

# Вывод результата  
echo "Success $SUCC_COUNT, Failed $FAIL_COUNT"  

  if [[ $EX_FAIL -eq 0 && $FAIL_COUNT -eq 0 ]]
        then 
        exit 0
        else 
        exit 1
  fi
}

# Функция подсчета успешных и неуспешных вызовов
REZULT_A ()
{
if test $? -eq 0
      then
        SUCC_COUNT=$(($SUCC_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A passed" >> $LOG_PATH/log.txt
      else
        FAIL_COUNT=$(($FAIL_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A failed" >> $LOG_PATH/log.txt
fi
}

# Function finishing script
FATAL ()
{
sudo killall -9 screen
screen -wipe
sudo killall -9 sipp
FAIL_COUNT=$(($FAIL_COUNT+999))
}

FUNC_TEST ()
{
        start_screen "$COUNT$T_NAME" "$COMMAND"  
        sleep 0.5
        check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else   
                $COMMAND_A
                REZULT_A
                wait_uas "$COUNT$T_NAME" 10
                if test $? -eq 99;then 
                        echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                        FATAL
                        FINISH
                fi
                sleep 2
        fi
}

FUNC_TEST3 ()
{
        start_screen "$COUNT$T_NAME" "$COMMAND"
        sleep 0.5
        check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else   
        	start_screen "2$COUNT$T_NAME" "$COMMAND2"  
	        sleep 0.5
        	check_screen "open" "2$COUNT$T_NAME"
        	if test $? -ne 0; then
                	echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                	FATAL
                	FINISH
        	else   
                	$COMMAND_A
                	REZULT_A
                	wait_uas "$COUNT$T_NAME" 100
                        if test $? -eq 99;then 
                                echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                                FATAL
                                FINISH
                        fi
			wait_uas "2$COUNT$T_NAME" 100
                	if test $? -eq 99;then 
                        	echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                        	FATAL
                        	FINISH
                	fi
                	sleep 2
		fi
        fi
}

# Registration users
T_NAME=Registration
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_A-$USER_C_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_B-pk.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_C_PK.csv -mi $IP -s $AUTH_C_PK -ap $PASS_C_PK -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_D_PK.csv -mi $IP -s $AUTH_D_PK -ap $PASS_D_PK -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_D_PK -recv_timeout 200s -timeout_error     
REZULT_A
sleep 2

# активируем услугу 
T_NAME=Configure_activate
$SRC_PATH/sswconf_pickup1.sh $DEV_USER $DEV_PASS $DEV_DOMAIN $EXTER_IP $USER_A $USER_B $USER_C_PK $USER_D_PK
REZULT_A

COUNT=1
T_NAME=free_after_busy
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/9-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2-uac_ssw_pk.xml -inf $TEMP_PATH/$USER_A-$USER_C_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 1; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_B-pk.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error -sleep 2"
FUNC_TEST3

COUNT=2
T_NAME=free_after_busy
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/9-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2-uac_ssw_pk.xml -inf $TEMP_PATH/$USER_A-$USER_C_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 1; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_B-pkC.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error -sleep 2"
FUNC_TEST3

COUNT=3
T_NAME=free_after_busy
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/9-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2-uac_ssw_pk.xml -inf $TEMP_PATH/$USER_A-$USER_C_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 1; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_B-pk1.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error -sleep 2"
FUNC_TEST3

COUNT=4
T_NAME=free_after_busy
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/9-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2-uac_ssw_pk.xml -inf $TEMP_PATH/$USER_A-$USER_D_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 1; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_B-pk.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error -sleep 2"
FUNC_TEST3

COUNT=5
T_NAME=free_after_busy
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/9-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2-uac_ssw_pk.xml -inf $TEMP_PATH/$USER_A-$USER_D_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 1; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_B-pkD.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error -sleep 2"
FUNC_TEST3

COUNT=6
# free after busy
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/9-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2-uac_ssw_pk.xml -inf $TEMP_PATH/$USER_A-$USER_D_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 1; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_B-pk2.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error -sleep 2"
FUNC_TEST3

COUNT=7
# free after busy
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/9r-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2r-uac_ssw_pk.xml -inf $TEMP_PATH/$USER_A-$USER_C_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 1; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_B-pk.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error -sleep 2"
FUNC_TEST3

COUNT=8
# free after busy
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/9r-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2r-uac_ssw_pk.xml -inf $TEMP_PATH/$USER_A-$USER_C_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 1; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_B-pkC.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error -sleep 2"
FUNC_TEST3

COUNT=9
# free after busy
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/9r-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2r-uac_ssw_pk.xml -inf $TEMP_PATH/$USER_A-$USER_C_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 1; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_B-pk1.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error -sleep 2"
FUNC_TEST3

COUNT=10
# free after busy
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/9r-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2r-uac_ssw_pk.xml -inf $TEMP_PATH/$USER_A-$USER_D_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 1; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_B-pk.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error -sleep 2"
FUNC_TEST3

COUNT=11
# free after busy
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/9r-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2r-uac_ssw_pk.xml -inf $TEMP_PATH/$USER_A-$USER_D_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 1; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_B-pkD.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error -sleep 2"
FUNC_TEST3

COUNT=12
# free after busy
COMMAND="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/9r-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C_PK -recv_timeout 200s -timeout_error ; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="$SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/2r-uac_ssw_pk.xml -inf $TEMP_PATH/$USER_A-$USER_D_PK.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 1; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_B-pk2.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error -sleep 2"
FUNC_TEST3

FINISH
