#!/bin/bash

# Путь к sipp 
SIPP_PATH=opt/sipp
LIB_PATH=tests/lib
SCRYPT_PATH=tests/scripts/tauxx214

# Библиотеки
source $LIB_PATH/screen_lib.sh
source $LIB_PATH/create_lib.sh

# Переменные командной строки
#DEV_USER=admin
#DEV_PASS=password
#DEV_DOMAIN=voip.local
EXTER_IP_A=192.168.118.119
EXTER_PORT_A=5060
IP_A=192.168.118.10
PORT_A=5060

C_COUNT=999999
