#!/usr/bin/expect -f

# Конфигурирование SSW для теста базовых вызовов. Версия ПО 3.3.
set user [lindex $argv 0]
set pass [lindex $argv 1]
set dom_name [lindex $argv 2]
set host [lindex $argv 3]

spawn ssh $user@$host -p 8023
expect "password:"
send "$pass\r"
expect -ex ":/$"

send "/domain/$dom_name/ss/permissions change * --unlock --enable mgm\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable 3way\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable alarm\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable acb\r" 
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable auto_redial\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable auto_redial_with_callback\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable black_list_in\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable black_list_out\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable call_recording\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable callback\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable cfb\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable cfnr\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable cfnr_type2\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable cfos\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable cft\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable cfu\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable cfu_type2\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable cgg\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable chold\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable chunt_cycle\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable chunt_group\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable chunt_manual\r"
expect -ex "?>"
send "yes\r"  
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable chunt_serial\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable clip\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable clir\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable ctr\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable cw\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable direct_call\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable dnd\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable follow_me\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable mcid\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable my_number\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable pickup\r"
expect -ex "?>"
send "yes\r"  
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable rbp\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable redial\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable rfc\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable speed_dial\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable sca\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable sco_black\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable sco_white\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable scr\r"
expect -ex "?>"
send "yes\r" 
expect -ex ":/$"
send "/domain/$dom_name/ss/permissions change * --unlock --enable teleconference_manager\r"
expect -ex "?>"
send "yes\r"
expect -ex ":/$"
send "exit\r"
expect eof