#!/bin/bash

# Тест SBC-subscribers. Версия ПО 1.5.0.
#
# Условия теста: создано одно направление

# Переменные командной строки
# $EXTER_IP_A:$EXTER_PORT_A SBC_IP_address:port 1
# $EXTER_IP_B:$EXTER_PORT_B SBC_IP_address:port 2
# $IP_A SIPP_IP_address
# $PORT_B SIPP_PORT1
# $PORT_B SIPP_PORT2

. tests/scripts/sbc_150/conf_subs

# Путь к скриптам
ROOT_DIR=$(pwd)
SRC_PATH=$ROOT_DIR/$SCRYPT_PATH/subscriber
create_dir $SRC_PATH/temp
TEMP_PATH=$SRC_PATH/temp
create_file $TEMP_PATH/ex_code.txt
create_dir log/sbc150_subscriber
LOG_PATH=log/sbc150_subscriber

create_file $LOG_PATH/log.txt

# Путь к sipp
#SIPP_PATH=../../../opt/sipp

# Переменные для подсчета успешных, неуспешных вызовов и номер теста
FAIL_COUNT=0
SUCC_COUNT=0
COUNT=0

# Создаем файлы с данными
echo "SEQUENTIAL;
$USER_A;$DOM_A;$USER_B;" > $TEMP_PATH/$USER_A-$USER_B.csv
echo "SEQUENTIAL;
$USER_B;$DOM_A;$USER_A;" > $TEMP_PATH/$USER_B-$USER_A.csv
echo "SEQUENTIAL;
sip:$USER_A@EXTER_IP_A:$EXTER_PORT_A" > $TEMP_PATH/sbc_routing.csv

FINISH ()
{

# Удаляем файлы с данными
sudo rm $TEMP_PATH/$USER_A-$USER_B.csv
sudo rm $TEMP_PATH/$USER_B-$USER_A.csv
sudo rm $TEMP_PATH/sbc_routing.csv

#    Читаем exit коды, чтобы убедиться, что все UAS отработали корректно.
EX_FAIL=0
while read line;do
     excode=`echo $line | cut -d ' ' -f 3`
     name=`echo $line | cut -d ' ' -f 1`
     echo "[DEBUG] Exit code from test $name equal $excode" >> $LOG_PATH/log.txt
     if [ "$excode" != "0" ];then
        EX_FAIL=1
        FAIL_COUNT=$(($FAIL_COUNT+1))
     fi
done < $TEMP_PATH/ex_code.txt

sudo rm $TEMP_PATH/ex_code.txt

# Вывод результата  
echo "Success $SUCC_COUNT, Failed $FAIL_COUNT"  

  if [[ $EX_FAIL -eq 0 && $FAIL_COUNT -eq 0 ]]
        then 
        exit 0
        else 
        exit 1
  fi
}

# Функция подсчета успешных и неуспешных вызовов
REZULT_A ()
{
if test $? -eq 0
      then
        SUCC_COUNT=$(($SUCC_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A passed" >> $LOG_PATH/log.txt
      else
        FAIL_COUNT=$(($FAIL_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A failed" >> $LOG_PATH/log.txt
fi
}

# Function finishing script
FATAL ()
{
sudo killall -9 screen
sudo screen -wipe
sudo killall -9 sipp
FAIL_COUNT=$(($FAIL_COUNT+999))
}

FUNC_TEST ()
{
        sudo_start_screen "$COUNT$T_NAME" "$COMMAND"  
        sleep 0.5
        sudo_check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else
                $COMMAND_A
                REZULT_A
                sudo_wait_uas "$COUNT$T_NAME" 10
                if test $? -eq 99;then 
                        echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                        FATAL
                        FINISH
                fi
                sleep 2
        fi
}

FUNC_TEST2 ()
{
        sudo_start_screen "$COUNT$T_NAME" "$COMMAND"  
        sleep 0.5
        sudo_check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else   
                $COMMAND_A
                REZULT_A
                $COMMAND_B
                REZULT_A
                sudo_wait_uas "$COUNT$T_NAME" 100
                if test $? -eq 99;then 
                        echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                        FATAL
                        FINISH
                fi
                sleep 2
        fi
}

FUNC_TEST3 ()
{
        sudo_start_screen "$COUNT$T_NAME" "$COMMAND"
        sleep 0.5
        sudo_check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else   
                sudo_start_screen "2$COUNT$T_NAME" "$COMMAND2"  
                sleep 0.5
                sudo_check_screen "open" "2$COUNT$T_NAME"
                if test $? -ne 0; then
                        echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                        FATAL
                        FINISH
                else   
                        $COMMAND_A
                        REZULT_A
                        sudo_wait_uas "$COUNT$T_NAME" 100
                        if test $? -eq 99;then 
                                echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                                FATAL
                                FINISH
                        fi
                        sudo_wait_uas "2$COUNT$T_NAME" 100
                        if test $? -eq 99;then 
                                echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                                FATAL
                                FINISH
                        fi
                        sleep 2
                fi
        fi
}


T_NAME=Set_DSCP_for_traffic
sudo iptables -t mangle -A OUTPUT -p udp -m udp --sport $PORT_A -j DSCP --set-dscp-class cs3 # mark SIP UDP packets with CS3
REZULT_A
sudo iptables -t mangle -A OUTPUT -p udp -m udp --sport 6000:8887 -j DSCP --set-dscp-class ef # mark RTP packets with EF
REZULT_A

T_NAME=Registrations

COUNT=$(($COUNT+1))
sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_bug_cont.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_0.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_all0.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_100s.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_0.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_0.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_noexp.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_0.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_0.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_rport.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_0.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_0.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_401.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_401.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_403.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_401_bug100.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_401.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=Adaptation_SoftX_3000
#12
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_wo_port.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_wo_port.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_407.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_407.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_503.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_503.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_0.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_all0.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_all3600.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_mul_cont.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_0.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_all0.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_mul_cont2.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_mul_cont2.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_0.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt" 
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_all0.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=NAT_disable
COUNT=$(($COUNT+1))
#22
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_norport_via2_2.xml -mi $IP_A -m 1 -nd -i $IP_A -p 5070 -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_norport_via2.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST3

echo Different_requests >> $LOG_PATH/log.txt
T_NAME=OPTIONS
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/optans.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/opt.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/optans_in_dial.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/opt_in_dial.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=UPDATE
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_update_prack.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_update_prack.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=Early_UPDATE
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_update_bugearly.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_update_bugearly.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=SUBSCRIBE
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/subans_presence.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/sub_difcont_presence.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/subans_msumm.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/sub_difcont_msumm.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/subans_ua_profile.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/sub_difcont_ua_profile.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/subans_keepalive.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/sub_difcont_keepalive.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

echo BASIC_Calls >> $LOG_PATH/log.txt
T_NAME=wo_100rel
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_1xx.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_1xx_sdp.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_plus_resh.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_plus_resh.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=Anonymous
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_anonym.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_anonym_name.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=w_o_1xx
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_wo_1xx.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=Cancel
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_cancel.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_cancel.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_bug_cancel_after_answer.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_bug_cancel_after_answer_no_to_tag.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=short
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_short.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=w_100_rel_PRACK
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_prack.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_prack.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_prack2.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_prack2.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_prack_fake_bug.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_prack.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_prack_bugappl.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=other_port_in_contact
#45
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_portcont_part1.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_portcont_part2_pj.xml -inf $TEMP_PATH/sbc_routing.csv -mi $IP_B -m 1 -nd -i $IP_B -p 5070 -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_prack_receivebye.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST3

T_NAME=delay_offer
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_bug53122.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_delayoffer_bug53122.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_delayoffer.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_183_sdp.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_delayoffer.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_delayoffer_prack.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_delayoffer_prack.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_delayoffer_prack2.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_delayoffer_prack2.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_delayoffer_wreinvite.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_delayoffer_wreinvite.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=4xx_5xx
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_401.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ans403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_481.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ans481_on_bye.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_503.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ans503.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=noACK
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_noack.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_noack.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=early_reInvite
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_tout5.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_reinv_bug.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=ROUTING
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_route.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_route_domain_480.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_rec_route.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_rec_route.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_rec_route.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_rec_route2.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_rec_route.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_rec_route_ip.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_rec_route_5067.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_rec_route_5067_2.xml -mi $IP_B -m 1 -nd -i $IP_B -p 5067 -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_pause_ack.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST3

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_bye.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_rec_route_5067.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_rec_route_5067_2.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p 5067 -recv_timeout 200s -timeout_error"
#FUNC_TEST3

T_NAME=TestSDP
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_nomap.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_nomap.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_dynmap.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_dynmap.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_g729a_cisco.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_sdp_cisco729a.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=Video
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_video.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_video.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=Inactive
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_t38_audio.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_t38.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_audio_t38.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_inact.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_video.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_inact.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_inact.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=2media_w_equal_ptype
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_2media_bugsdp.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_sdp_twomedia_eq_pt.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=sendonly_receiveonly
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_ro.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_so.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_so.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ro.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=errors_in_SDP
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_488.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_errorcodec.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_sdpbug2.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_sdpbug3.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_sdpbug4.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_nortell.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=reduce_media
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_red.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_red.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=modem
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_gpmd.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=rfc_2833_errors
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_2833_fmtpbug.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_sdp_rfc2833_empty_fmtp.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_2833_fmtpbug2.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_sdp_rfc2833_wo_fmtp.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=different_SDP_in_1xx
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_1xx_diff_sdp.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=Adaptation_nortell_off
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_prack3_dif_sdp.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_prack3.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

echo Media >> $LOG_PATH/log.txt
T_NAME=test_codecs
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_g723_30_63a.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -rtp_echo -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_g723_30_63_annexa_audio.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_g726dyn.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -rtp_echo -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_g726dyn_audio.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_g729_80.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -rtp_echo -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_g729_80_audio.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_pcmu30.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -rtp_echo -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_pcmu30_audio.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

echo DTMF-FEATURES >> $LOG_PATH/log.txt
T_NAME=convert_RFC-INFO
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_rfc2833_pt96.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_rfc2833_pt96.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_rfc2833_pt96_2.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_rfc2833_pt96_2.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=translate_DTMF
#92
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_rfc2833_pt96_dtmf.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_rfc2833_pt96_dtmf.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

echo "SSup SERVICES" >> $LOG_PATH/log.txt
T_NAME=3xx
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p 5070 -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND2="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_305.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_181m.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST3

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_ss_hold.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ss_hold.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_ss_hold_0000.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ss_hold.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=ct_not_finished
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_refer_wonotify.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_refer_wonotify.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=diversion
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_div_3times_sip.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_div_3times_tel.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=AdaptationHuawei
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_rcv_info.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_sbc_huawei.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=adaptationSI3000
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uas_1xx.xml -mi $IP_A -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uac_user_phone.xml -inf $TEMP_PATH/$USER_B-$USER_A.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_B -recv_timeout 200s -timeout_error"
#FUNC_TEST

T_NAME=translateDTMF
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_sbc_info_dtmf.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_sbc_info_dtmf.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
#FUNC_TEST

echo TIMERS >> $LOG_PATH/log.txt
T_NAME=TimerC
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_tC.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 600s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_tC.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 600s -timeout_error"
#FUNC_TEST

T_NAME=timerRFC4028
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_timer_tranzsbc_uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 600s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_timer_tranzsbc_uas.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 600s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_timer_tranzsbc_uac.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 600s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_timer_tranzsbc_uac.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 600s -timeout_error"
#FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_timer_update.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 600s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_timer_update.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 600s -timeout_error"
#FUNC_TEST

FINISH
