#!/bin/bash

# Тест TAU

# Переменные командной строки
# $EXTER_IP_A:$EXTER_PORT_A SBC_IP_address:port 1
# $EXTER_IP_B:$EXTER_PORT_B SBC_IP_address:port 2
# $IP_A SIPP_IP_address
# $PORT_B SIPP_PORT1
# $PORT_B SIPP_PORT2

. tests/scripts/tauxx214/conf

# Путь к скриптам
ROOT_DIR=$(pwd)
SRC_PATH=$ROOT_DIR/$SCRYPT_PATH/regans401
create_dir $SRC_PATH/temp
TEMP_PATH=$SRC_PATH/temp
create_file $TEMP_PATH/ex_code.txt
create_dir log/tauxx214_regans401
LOG_PATH=log/tauxx214_regans401

create_file $LOG_PATH/log.txt

# Путь к sipp
#SIPP_PATH=../../../opt/sipp

# Переменные для подсчета успешных, неуспешных вызовов и номер теста
FAIL_COUNT=0
SUCC_COUNT=0
COUNT=0

FINISH ()
{

#    Читаем exit коды, чтобы убедиться, что все UAS отработали корректно.
EX_FAIL=0
while read line;do
     excode=`echo $line | cut -d ' ' -f 3`
     name=`echo $line | cut -d ' ' -f 1`
     echo "[DEBUG] Exit code from test $name equal $excode" >> $LOG_PATH/log.txt
     if [ "$excode" != "0" ];then
        EX_FAIL=1
        FAIL_COUNT=$(($FAIL_COUNT+1))
     fi
done < $TEMP_PATH/ex_code.txt

sudo rm $TEMP_PATH/ex_code.txt

# Вывод результата  
echo "Success $SUCC_COUNT, Failed $FAIL_COUNT"  

  if [[ $EX_FAIL -eq 0 && $FAIL_COUNT -eq 0 ]]
        then 
        exit 0
        else 
        exit 1
  fi
}

# Функция подсчета успешных и неуспешных вызовов
REZULT_A ()
{
if test $? -eq 0
      then
        SUCC_COUNT=$(($SUCC_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A passed" >> $LOG_PATH/log.txt
      else
        FAIL_COUNT=$(($FAIL_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A failed" >> $LOG_PATH/log.txt
fi
}

# Function finishing script
FATAL ()
{
sudo killall -9 screen
sudo screen -wipe
sudo killall -9 sipp
FAIL_COUNT=$(($FAIL_COUNT+999))
}

FUNC_TEST ()
{
        sudo_start_screen "$COUNT$T_NAME" "$COMMAND"  
        sleep 0.5
        sudo_check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else   
                $COMMAND_A
                REZULT_A
                sudo_wait_uas "$COUNT$T_NAME" 30
                if test $? -eq 99;then 
                        echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                        FATAL
                        FINISH
                fi
                sleep 2
        fi
}

COUNT=$(($COUNT+1))
T_NAME=Registrations
sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/regans_401.xml -mi $IP_A -m $C_COUNT -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

FINISH
