#!/bin/bash

# Тест SBC-subs-nat. Версия ПО 1.5.0.
#
# Условия теста: создано одно направление

# Переменные командной строки
# $EXTER_IP_A:$EXTER_PORT_A SBC_IP_address:port 1
# $EXTER_IP_B:$EXTER_PORT_B SBC_IP_address:port 2
# $IP_A SIPP_IP_address
# $PORT_B SIPP_PORT1
# $PORT_B SIPP_PORT2

. tests/scripts/sbc_150/conf_nat

# Путь к скриптам
ROOT_DIR=$(pwd)
SRC_PATH=$ROOT_DIR/$SCRYPT_PATH/nat
create_dir $SRC_PATH/temp
TEMP_PATH=$SRC_PATH/temp
create_file $TEMP_PATH/ex_code.txt
create_dir log/sbc150_nat
LOG_PATH=log/sbc150_nat

create_file $LOG_PATH/log.txt

# Путь к sipp
#SIPP_PATH=../../../opt/sipp

# Переменные для подсчета успешных, неуспешных вызовов и номер теста
FAIL_COUNT=0
SUCC_COUNT=0
COUNT=0

# Создаем файлы с данными
echo "SEQUENTIAL;
$USER_A;$DOM_A;$USER_B;" > $TEMP_PATH/$USER_A-$USER_B.csv
echo "SEQUENTIAL;
$USER_B;$DOM_A;$USER_A;" > $TEMP_PATH/$USER_B-$USER_A.csv
echo "SEQUENTIAL; 
$USER_NR;$DOM_A;$USER_B;" > $TEMP_PATH/$USER_NR.csv
echo "SEQUENTIAL;
$USER_B;$DOM_A;$USER_NR;" > $TEMP_PATH/$USER_B-$USER_NR.csv

FINISH ()
{

# Удаляем файлы с данными
sudo rm $TEMP_PATH/$USER_A-$USER_B.csv
sudo rm $TEMP_PATH/$USER_B-$USER_A.csv
sudo rm $TEMP_PATH/$USER_NR.csv

#    Читаем exit коды, чтобы убедиться, что все UAS отработали корректно.
EX_FAIL=0
while read line;do
     excode=`echo $line | cut -d ' ' -f 3`
     name=`echo $line | cut -d ' ' -f 1`
     echo "[DEBUG] Exit code from test $name equal $excode" >> $LOG_PATH/log.txt
     if [ "$excode" != "0" ];then
        EX_FAIL=1
        FAIL_COUNT=$(($FAIL_COUNT+1))
     fi
done < $TEMP_PATH/ex_code.txt

sudo rm $TEMP_PATH/ex_code.txt

# Вывод результата  
echo "Success $SUCC_COUNT, Failed $FAIL_COUNT"  

  if [[ $EX_FAIL -eq 0 && $FAIL_COUNT -eq 0 ]]
        then 
        exit 0
        else 
        exit 1
  fi
}

# Функция подсчета успешных и неуспешных вызовов
REZULT_A ()
{
if test $? -eq 0
      then
        SUCC_COUNT=$(($SUCC_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A passed" >> $LOG_PATH/log.txt
      else
        FAIL_COUNT=$(($FAIL_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A failed" >> $LOG_PATH/log.txt
fi
}

# Function finishing script
FATAL ()
{
sudo killall -9 screen
sudo screen -wipe
sudo killall -9 sipp
FAIL_COUNT=$(($FAIL_COUNT+999))
}

FUNC_TEST ()
{
        sudo_start_screen "$COUNT$T_NAME" "$COMMAND"  
        sleep 0.5
        sudo_check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else   
                $COMMAND_A
                REZULT_A
                sudo_wait_uas "$COUNT$T_NAME" 30
                if test $? -eq 99;then 
                        echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                        FATAL
                        FINISH
                fi
                sleep 2
        fi
}

FUNC_TEST2 ()
{
        sudo_start_screen "$COUNT$T_NAME" "$COMMAND"  
        sleep 0.5
        sudo_check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else   
                $COMMAND_A
                REZULT_A
                $COMMAND_B
                REZULT_A
                sudo_wait_uas "$COUNT$T_NAME" 100
                if test $? -eq 99;then 
                        echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                        FATAL
                        FINISH
                fi
                sleep 2
        fi
}

COUNT=$(($COUNT+1))
T_NAME=Registrations
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_0.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_all0.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_0.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_all0.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=Adaptation_SoftX3000
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_wo_port.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_wo_port.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_0.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_all0.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=NAT_enable
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_norport_via.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

echo "Different requests" >> $LOG_PATH/log.txt
T_NAME=OPTIONS
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/optans.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/opt.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/optans_in_dial.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/opt_in_dial.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=UPDATE
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_update_prack.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_update_prack.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=Early_UPDATE
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_update_bugearly.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_update_bugearly.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

echo "BASIC Calls" >> $LOG_PATH/log.txt
TNAME=wo_100rel
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_1xx.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_1xx_sdp.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uas_1xx.xml -mi $IP_A -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uac.xml -inf $TEMP_PATH/$USER_B-$USER_A.csv -mi $IP_B -s $USER_B -ap $AUTH_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uas_1xx_sdp.xml -mi $IP_A -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uac.xml -inf $TEMP_PATH/$USER_B-$USER_A.csv -mi $IP_B -s $USER_B -ap $AUTH_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=w_100rel
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_prack.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_prack.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_prack2.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_prack2.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uas_prack.xml -mi $IP_A -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uac_prack.xml -inf $TEMP_PATH/$USER_B-$USER_A.csv -mi $IP_B -s $USER_B -ap $AUTH_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uas_prack2.xml -mi $IP_A -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uac_prack2.xml -inf $TEMP_PATH/$USER_B-$USER_A.csv -mi $IP_B -s $USER_B -ap $AUTH_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=calls_fromTo_not_reg
COUNT=$(($COUNT+1))
sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uac_ans404.xml -inf $TEMP_PATH/$USER_B-$USER_NR.csv -mi $IP_B -s $USER_B -ap $AUTH_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A

COUNT=$(($COUNT+1))
sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ans403.xml -inf $TEMP_PATH/$USER_NR.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

COUNT=$(($COUNT+1))
sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uac_no_ans.xml -inf $TEMP_PATH/$USER_B-$USER_NR.csv -mi $IP_C -s $USER_B -ap $AUTH_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_C -p $PORT_C -recv_timeout 200s -timeout_error
REZULT_A

T_NAME=ROUTING
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_route.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_route_domain_480.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_rec_route_ip.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_bye.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_rec_route_5067_nat.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
COMMAND_B="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_rec_route_5067_2.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST2

echo Media >> $LOG_PATH/log.txt
T_NAME=test_codecs
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_g723_30_63a.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -rtp_echo -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_g723_30_63_annexa_audio.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_g726dyn.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -rtp_echo -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_g726dyn_audio.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_g729_80.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -rtp_echo -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_g729_80_audio.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_pcmu30.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -rtp_echo -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_pcmu30_audio.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

echo "media control RTP, RTCP" >> $LOG_PATH/log.txt
T_NAME=RTCP
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_sp_rtcp.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_sp_rtcp.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=RTCP_control
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_sp_rtcp_timer.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

T_NAME=Fail2ban
COUNT=$(($COUNT+1))
COMMAND="$SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_603.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ans603.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="$SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_603.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ans603.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="$SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_603.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ans603.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error" 
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="$SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_403.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ans403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="$SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_403.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ans403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="$SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_403.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ans403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="$SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/uas_403.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_ans403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="$SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_0.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_0.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_403.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_403.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

if  [ "$IP_A" != "$IP_B" ];then
COUNT=$(($COUNT+1))
COMMAND="sudo $SIPP_PATH/sipp $EXTER_IP_B:$EXTER_PORT_B -sf $SRC_PATH/regans_403.xml -mi $IP_B -m 1 -nd -i $IP_B -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/reg_403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST
fi

echo "FAIL2BAN will work only with REGISTER" >> $LOG_PATH/log.txt
COUNT=$(($COUNT+1))
sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_no_ans.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

COUNT=$(($COUNT+1))
sudo $SIPP_PATH/sipp $EXTER_IP_A:$EXTER_PORT_A -sf $SRC_PATH/uac_no_ans.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP_A -s $USER_A -ap $AUTH_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP_A -p $PORT_A -recv_timeout 200s -timeout_error 
REZULT_A

FINISH
