#!/bin/bash

# Тест autoredial. 
# 
# Условия теста: создано два SIP-абонента 
#              : активированы услуги (выполнен скрипт sswconf_ss_perm.sh)

# Переменные командной строки
# $DEV_USER SSW_cocon_user
# $DEV_PASS SSW_cocon_password
# $DEV_DOMAIN SSW_domain
# $EXTER_IP:$EXTER_PORT SSW_IP_address
# $IP SIPP_IP_address
# $USER_A Number of SIP USER A

. ./conf

# Библиотеки
source $LIB_PATH/screen_lib.sh
source $LIB_PATH/create_lib.sh

# Путь к скриптам
ROOT_DIR=$(pwd)
SRC_PATH=$ROOT_DIR/$SCRYPT_PATH/autoredial
create_dir $SRC_PATH/temp
TEMP_PATH=$SRC_PATH/temp
create_file $TEMP_PATH/ex_code.txt
create_dir log/ssw350_autoredial
LOG_PATH=log/ssw350_autoredial

create_file $LOG_PATH/log.txt

# Путь к sipp
#SIPP_PATH=../../../opt/sipp

# Переменные для подсчета успешных, неуспешных вызовов и номер теста
FAIL_COUNT=0
SUCC_COUNT=0
COUNT=0

# Создаем файлы с данными
echo "SEQUENTIAL;
$USER_A;$DOM_A;" > $TEMP_PATH/$USER_A.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;" > $TEMP_PATH/$USER_B.csv
echo "SEQUENTIAL;
$USER_NR;$DOM_NR;*$CFOOS_KOD*$USER_B#;#$CFOOS_KOD#" > $TEMP_PATH/$USER_NR.csv
echo "SEQUENTIAL;
$USER_A;$DOM_A;*$AUTORED_BUSY_KOD*$USER_B#;" > $TEMP_PATH/$USER_A-busy.csv
echo "SEQUENTIAL;
$USER_A;$DOM_A;*$AUTORED_ALL_KOD*$USER_B#;" > $TEMP_PATH/$USER_A-all.csv
echo "SEQUENTIAL;
$USER_A;$DOM_A;*$AUTORED_ALL_KOD*$USER_NR#;" > $TEMP_PATH/$USER_A-$USER_NR.csv
echo "SEQUENTIAL;
$USER_C;$DOM_C;$USER_B" > $TEMP_PATH/$USER_C.csv

FINISH ()
{
# Unregistration
COUNT=$(($COUNT+1))
T_NAME=UnRegistration
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/$USER_A.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/$USER_B.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/$USER_C.csv -mi $IP -s $AUTH_C -ap $PASS_C -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_C -recv_timeout 200s -timeout_error
REZULT_A

# Возвращаем исходные настройки
$SRC_PATH/sswconf_autored2.sh $DEV_USER $DEV_PASS $DEV_DOMAIN $EXTER_IP $USER_A
REZULT_A

# Удаляем файлы с данными
sudo rm $TEMP_PATH/$USER_A.csv
sudo rm $TEMP_PATH/$USER_B.csv
sudo rm $TEMP_PATH/$USER_C.csv
sudo rm $TEMP_PATH/$USER_NR.csv
sudo rm $TEMP_PATH/$USER_A-busy.csv
sudo rm $TEMP_PATH/$USER_A-all.csv
sudo rm $TEMP_PATH/$USER_A-$USER_NR.csv

#    Читаем exit коды, чтобы убедиться, что все UAS отработали корректно.
EX_FAIL=0
while read line;do
     excode=`echo $line | cut -d ' ' -f 3`
     name=`echo $line | cut -d ' ' -f 1`
     echo "[DEBUG] Exit code from test $name equal $excode" >> $LOG_PATH/log.txt
     if [ "$excode" != "0" ];then
        EX_FAIL=1
        FAIL_COUNT=$(($FAIL_COUNT+1))
     fi
done < $TEMP_PATH/ex_code.txt

sudo rm $TEMP_PATH/ex_code.txt

# Вывод результата  
echo "Success $SUCC_COUNT, Failed $FAIL_COUNT"  

  if [[ $EX_FAIL -eq 0 && $FAIL_COUNT -eq 0 ]]
        then 
        exit 0
        else 
        exit 1
  fi
}

# Функция подсчета успешных и неуспешных вызовов
REZULT_A ()
{
if test $? -eq 0
      then
        SUCC_COUNT=$(($SUCC_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A passed" >> $LOG_PATH/log.txt
      else
        FAIL_COUNT=$(($FAIL_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A failed" >> $LOG_PATH/log.txt
fi
}

# Function finishing script
FATAL ()
{
sudo killall -9 screen
screen -wipe
sudo killall -9 sipp
FAIL_COUNT=$(($FAIL_COUNT+999))
}

FUNC_TEST ()
{
        start_screen "$COUNT$T_NAME" "$COMMAND"  
        sleep 0.5
        check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else   
                $COMMAND_A
                REZULT_A
                wait_uas "$COUNT$T_NAME" 10
                if test $? -eq 99;then 
                        echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                        FATAL
                        FINISH
                fi
                sleep 2
        fi
}

FUNC_TEST3 ()
{
        start_screen "$COUNT$T_NAME" "$COMMAND"
        sleep 0.5
        check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else   
        	start_screen "2$COUNT$T_NAME" "$COMMAND2"  
	        sleep 0.5
        	check_screen "open" "2$COUNT$T_NAME"
        	if test $? -ne 0; then
                	echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                	FATAL
                	FINISH
        	else   
                	$COMMAND_A
                	REZULT_A
                	wait_uas "$COUNT$T_NAME" 100
                        if test $? -eq 99;then 
                                echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                                FATAL
                                FINISH
                        fi
			wait_uas "2$COUNT$T_NAME" 100
                	if test $? -eq 99;then 
                        	echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                        	FATAL
                        	FINISH
                	fi
                	sleep 2
		fi
        fi
}

# Конфигурируем услугу и таймера
$SRC_PATH/sswconf_autored1.sh $DEV_USER $DEV_PASS $DEV_DOMAIN $EXTER_IP $USER_A
REZULT_A
$SRC_PATH/sswconf_timer.sh $DEV_USER $DEV_PASS $DEV_DOMAIN $EXTER_IP
REZULT_A

# Registration users
T_NAME=Registration
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_A.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_B.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_C.csv -mi $IP -s $AUTH_C -ap $PASS_C -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_C -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/$USER_NR.csv -mi $IP -s $AUTH_NR -ap $PASS_NR -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_NR -recv_timeout 200s -timeout_error
REZULT_A

COUNT=1
T_NAME="busy_at_all"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ans486.xml -mi $IP -m 6 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_ans480.xml -inf $TEMP_PATH/$USER_A-busy.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

COUNT=2
T_NAME="free_after_busy"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_r1i.xml -inf $TEMP_PATH/$USER_A-busy.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 3"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ans486.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ans600.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ans486.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ans600.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ans486.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_send_bye.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
FUNC_TEST

COUNT=3
T_NAME="free_after_not_ans"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_r1i.xml -inf $TEMP_PATH/$USER_A-all.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 3"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_cancel.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_send_bye.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
FUNC_TEST

COUNT=4
T_NAME=ssw_detect_busy_kodBusy
COMMAND2="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_10s.xml -inf $TEMP_PATH/$USER_C.csv -mi $IP -s $AUTH_C -ap $PASS_C -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_C -timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_r1i.xml -inf $TEMP_PATH/$USER_A-busy.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 3"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ssw1.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_send_bye.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
FUNC_TEST3

COUNT=5
T_NAME=ssw_detect_busy_kodAll
COMMAND2="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_10s.xml -inf $TEMP_PATH/$USER_C.csv -mi $IP -s $AUTH_C -ap $PASS_C -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_C -timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_r1i.xml -inf $TEMP_PATH/$USER_A-all.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 3"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ssw1.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_send_bye.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
FUNC_TEST3

COUNT=6
T_NAME="to not reg"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_ans480.xml -inf $TEMP_PATH/$USER_A-$USER_NR.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

COUNT=7
echo "with cfoos to busy and free later" >> $LOG_PATH/log.txt
T_NAME=CFOOS_activation
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_NR.csv -mi $IP -s $AUTH_NR -ap $PASS_NR -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_NR -recv_timeout 200s -timeout_error
REZULT_A 
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2.xml -inf $TEMP_PATH/$USER_NR.csv -mi $IP -s $AUTH_NR -ap $PASS_NR -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_NR -recv_timeout 200s -timeout_error
REZULT_A 
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/$USER_NR.csv -mi $IP -s $AUTH_NR -ap $PASS_NR -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_NR -recv_timeout 200s -timeout_error
REZULT_A 

T_NAME="free_after_busy_after_cfoos"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_r1i.xml -inf $TEMP_PATH/$USER_A-$USER_NR.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error -sleep 3"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ans486.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ans600.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ans486.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ans600.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_ans486.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error && \
$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uas_send_bye.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
FUNC_TEST 
sleep 3

T_NAME=CFOOS_deactivate
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_NR.csv -mi $IP -s $AUTH_NR -ap $PASS_NR -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_NR -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field3.xml -inf $TEMP_PATH/$USER_NR.csv -mi $IP -s $AUTH_NR -ap $PASS_NR -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_NR -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/$USER_NR.csv -mi $IP -s $AUTH_NR -ap $PASS_NR -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_NR -recv_timeout 200s -timeout_error
REZULT_A

FINISH
