#!/bin/bash

# Тест услуги "Белый список" - SCA, SCO_white.
#
# Условия теста: создано два SIP-абонента и один SIP-транк
#              : активированы услуги (выполнен скрипт sswconf_ss_perm.sh)

# Переменные командной строки
# $EXTER_IP:$EXTER_PORT SSW_IP_address
# $IP SIPP_IP_address

. ./conf

# Библиотеки
source $LIB_PATH/screen_lib.sh
source $LIB_PATH/create_lib.sh

# Путь к скриптам
ROOT_DIR=$(pwd)
SRC_PATH=$ROOT_DIR/$SCRYPT_PATH/sca
create_dir $SRC_PATH/temp
TEMP_PATH=$SRC_PATH/temp
create_file $TEMP_PATH/ex_code.txt
create_dir log/ssw350_sca
LOG_PATH=log/ssw350_sca

create_file $LOG_PATH/log.txt

# Путь к sipp
#SIPP_PATH=../../../opt/sipp

# Переменные для подсчета успешных, неуспешных вызовов и номер теста
FAIL_COUNT=0
SUCC_COUNT=0
COUNT=0

# Создаем файлы с данными
echo "SEQUENTIAL;
$USER_A;$DOM_A;*$SCO_WH_KOD*$PIN_A#;#$SCO_WH_KOD*$PIN_A#;*$SCO_WH_KOD*$PIN_A*0*$USER_B_NC#;*$SCO_WH_KOD*$PIN_A*1*$USER_B_NC#;*$SCO_WH_KOD*$PIN_A*$USER_B#;#$SCO_WH_KOD*$PIN_A*0#;#$SCO_WH_KOD*$PIN_A*1#;#$SCO_WH_KOD*$PIN_A*$USER_B#;*$SCO_WH_KOD*$PIN_A*2*$USER_C_MF#;#$SCO_WH_KOD*$PIN_A*$USER_C_MF#;" > $TEMP_PATH/$USER_A-scasco.csv
echo "SEQUENTIAL;
$USER_A;$DOM_A;*$SCO_BL_KOD*$PIN_A#;#$SCO_BL_KOD*$PIN_A#;" > $TEMP_PATH/$USER_A-scrsco.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;*$SCA_KOD*$PIN_B#;#$SCA_KOD*$PIN_B#;*$SCA_KOD*$PIN_B*0*$USER_A_NC#;*$SCA_KOD*$PIN_B*1*$USER_A_NC#;*$SCA_KOD*$PIN_B*$USER_A#;#$SCA_KOD*$PIN_B*0#;#$SCA_KOD*$PIN_B*1#;#$SCA_KOD*$PIN_B*$USER_A#;*$SCA_KOD*$PIN_B*2*$USER_C#;#$SCA_KOD*$PIN_B*$USER_C#;" > $TEMP_PATH/$USER_B-scasco.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;*$SCR_KOD*$PIN_B#;#$SCR_KOD*$PIN_B#;*$SCR_KOD*$PIN_B*1*$USER_A_NC#;#$SCR_KOD*$PIN_B*0#;" > $TEMP_PATH/$USER_B-scrsco.csv
echo "SEQUENTIAL;
$USER_A;$DOM_A;$USER_B;" > $TEMP_PATH/$USER_A-$USER_B.csv
echo "SEQUENTIAL;
$USER_A;$DOM_A;$USER_C;" > $TEMP_PATH/$USER_A-$USER_C.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;$USER_A;" > $TEMP_PATH/$USER_B-$USER_A.csv
echo "SEQUENTIAL;
$USER_B;$DOM_B;$USER_C;" > $TEMP_PATH/$USER_B-$USER_C.csv
echo "SEQUENTIAL;
$USER_C;$DOM_C;$USER_A;" > $TEMP_PATH/$USER_C-$USER_A.csv
echo "SEQUENTIAL;
$USER_C;$DOM_C;$USER_B;" > $TEMP_PATH/$USER_C-$USER_B.csv
echo "SEQUENTIAL;
$USER_D;$DOM_C;$USER_B;" > $TEMP_PATH/$USER_D-$USER_B.csv

FINISH ()
{
# Unregistration
COUNT=$(($COUNT+1))
T_NAME=UnRegistration
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth0.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A

# Удаляем файлы с данными
sudo rm $TEMP_PATH/$USER_A-scasco.csv
sudo rm $TEMP_PATH/$USER_B-scasco.csv
sudo rm $TEMP_PATH/$USER_A-scrsco.csv
sudo rm $TEMP_PATH/$USER_B-scrsco.csv
sudo rm $TEMP_PATH/$USER_A-$USER_B.csv
sudo rm $TEMP_PATH/$USER_A-$USER_C.csv
sudo rm $TEMP_PATH/$USER_B-$USER_A.csv
sudo rm $TEMP_PATH/$USER_B-$USER_C.csv
sudo rm $TEMP_PATH/$USER_C-$USER_A.csv
sudo rm $TEMP_PATH/$USER_C-$USER_B.csv
sudo rm $TEMP_PATH/$USER_D-$USER_B.csv

#    Читаем exit коды, чтобы убедиться, что все UAS отработали корректно.
EX_FAIL=0
while read line;do
     excode=`echo $line | cut -d ' ' -f 3`
     name=`echo $line | cut -d ' ' -f 1`
     echo "[DEBUG] Exit code from test $name equal $excode" >> $LOG_PATH/log.txt
     if [ "$excode" != "0" ];then
        EX_FAIL=1
        FAIL_COUNT=$(($FAIL_COUNT+1))
     fi
done < $TEMP_PATH/ex_code.txt

sudo rm $TEMP_PATH/ex_code.txt

# Вывод результата  
echo "Success $SUCC_COUNT, Failed $FAIL_COUNT"  

  if [[ $EX_FAIL -eq 0 && $FAIL_COUNT -eq 0 ]]
        then 
        exit 0
        else 
        exit 1
  fi
}

# Функция подсчета успешных и неуспешных вызовов
REZULT_A ()
{
if test $? -eq 0
      then
        SUCC_COUNT=$(($SUCC_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A passed" >> $LOG_PATH/log.txt
      else
        FAIL_COUNT=$(($FAIL_COUNT+1))
        echo "[DEBUG] Test $COUNT $T_NAME side A failed" >> $LOG_PATH/log.txt
fi
}

# Function finishing script
FATAL ()
{
sudo killall -9 screen
screen -wipe
sudo killall -9 sipp
FAIL_COUNT=$(($FAIL_COUNT+999))
}

FUNC_TEST ()
{
        start_screen "$COUNT$T_NAME" "$COMMAND"  
        sleep 0.5
        check_screen "open" "$COUNT$T_NAME"
        if test $? -ne 0; then
                echo "Fatal error - screen failed" >> $LOG_PATH/log.txt
                FATAL
                FINISH
        else   
                $COMMAND_A
                REZULT_A
                wait_uas "$COUNT$T_NAME" 10
                if test $? -eq 99;then 
                        echo "Fatal error - screen timeout" >> $LOG_PATH/log.txt
                        FATAL
                        FINISH
                fi
                sleep 2
        fi
}

# Registration users
T_NAME=Registration
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 20s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/reg_auth.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 20s -timeout_error
REZULT_A

T_NAME="Control of deactivation of SCA and SCO features"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field3.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field3.xml -inf $TEMP_PATH/$USER_A-scrsco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field3.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 120s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field3.xml -inf $TEMP_PATH/$USER_B-scrsco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 120s -timeout_error 
REZULT_A

T_NAME="Activation of SCO_WH and SCO_BL features to user A (WH will be work with prio)"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2.xml -inf $TEMP_PATH/$USER_A-scrsco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A

T_NAME="Control extraction of user B  and user C numbers from white list"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field9.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field11.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A

echo "Test SCO_WHITE" >> $LOG_PATH/log.txt
COUNT=1
T_NAME="No numbers in list, all calls rejected"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_A-$USER_C.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A

COUNT=2
T_NAME="Add num in 0 string in list. Must be error"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field4.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A
T_NAME="Add num user_B_not_compl, user_C_modify in list and test"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field5.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field10.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A

T_NAME="Calls"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_A-$USER_C.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

T_NAME="delete USER_C_MF and USER_B_NC from list"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field11.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field7.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A
T_NAME="Call to USER_B"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 120s -timeout_error
REZULT_A
sleep 2

COUNT=3
T_NAME="Add num user_B_not_compl in list and test"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field5.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

T_NAME="Calls"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_A-$USER_C.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="delete USER_B_NC from list"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field8.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="Call to USER_B"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
sleep 2

COUNT=4
T_NAME="Add num user_B_not_compl in list and test"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field6.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="Calls"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_A-$USER_C.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="delete USER_B_NC from list"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field9.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="Call to USER_B"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
sleep 3

COUNT=5
T_NAME="Deactivation of SCA and SCO features"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field3.xml -inf $TEMP_PATH/$USER_A-scasco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field3.xml -inf $TEMP_PATH/$USER_A-scrsco.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="Call_to_USERB__success"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME="Call_to_USERC__success"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_C -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_A-$USER_C.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

echo "Test SCA" >> $LOG_PATH/log.txt
COUNT=6
T_NAME="Activation of SCA and SCR features to user B (WH will be work with prio)"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2.xml -inf $TEMP_PATH/$USER_B-scrsco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A

T_NAME="Control extraction of user A and user C numbers from white list"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field9.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field11.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A

T_NAME="Call to USER_B"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

COUNT=7
T_NAME="Add num in 0 string in list. Must be error"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field4.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="Add num user A not compl in white and black list. Prio White"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field5.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field4.xml -inf $TEMP_PATH/$USER_B-scrsco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="Call_to_USER_B__success_A"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME="Call to USER_B, fail C"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_C-$USER_B.csv -mi $IP -s $AUTH_C -ap $PASS_C -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_C -recv_timeout 200s -timeout_error
REZULT_A
sleep 2
T_NAME="Extract number of user A from white, black list and deactivate SCR"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field5.xml -inf $TEMP_PATH/$USER_B-scrsco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field3.xml -inf $TEMP_PATH/$USER_B-scrsco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field7.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="Call to USER_B"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

COUNT=8
T_NAME="Add num user A in white list"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field5.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="Call_to_USER_B__success_A"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME="Call to USER_B, fail C"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_C-$USER_B.csv -mi $IP -s $AUTH_C -ap $PASS_C -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_C -recv_timeout 200s -timeout_error
REZULT_A
sleep 2
T_NAME="Extract number of user A from white list"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field8.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="Call to USER_B"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

COUNT=9
T_NAME="Add num user A in white list"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field6.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="Call_to_USER_B__successA"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST
T_NAME="Call to USER_B, fail C"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_C-$USER_B.csv -mi $IP -s $AUTH_C -ap $PASS_C -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_C -recv_timeout 200s -timeout_error
REZULT_A
sleep 2
T_NAME="Extract number of user A from white list"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field9.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="Call to USER_B"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field2_403.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error
REZULT_A

COUNT=10
T_NAME="Add num user C modify in white list"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field10.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A
T_NAME="Call_to_USER_B__success"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_D-$USER_B.csv -mi $IP -s $AUTH_C -ap $PASS_C -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_D -recv_timeout 200s -timeout_error"
FUNC_TEST
sleep 2
T_NAME="Extract number of user C from white list"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field11.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A

COUNT=11
T_NAME="Deactivation of SCA feature"
sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/uac_field3.xml -inf $TEMP_PATH/$USER_B-scasco.csv -mi $IP -s $AUTH_B -ap $PASS_B -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error
REZULT_A

COUNT=12
T_NAME="Call_to_USER_B__success"
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_C-$USER_B.csv -mi $IP -s $AUTH_C -ap $PASS_C -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_C -recv_timeout 200s -timeout_error"
FUNC_TEST
sleep 2
COUNT=13
COMMAND="$SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uas_ssw.xml -mi $IP -m 1 -nd -i $IP -p $PORT_B -recv_timeout 200s -timeout_error; echo $COUNT $T_NAME \$? >> $TEMP_PATH/ex_code.txt"
COMMAND_A="sudo $SIPP_PATH/sipp $EXTER_IP:$EXTER_PORT -sf $SRC_PATH/1-uac_ssw.xml -inf $TEMP_PATH/$USER_A-$USER_B.csv -mi $IP -s $AUTH_A -ap $PASS_A -rtp_echo -l 1 -r 1 -m 1 -nd -i $IP -p $PORT_A -recv_timeout 200s -timeout_error"
FUNC_TEST

FINISH

